server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.sec.samsung.net/RAM7-MVSSL-Cloud/playground
          search-paths: config/
          username: ross-wang
          password: --------
#        native:
#          search-locations: file:///Users/ross.wang/Documents/GitHub/playground/config/demoservice